CATEGORIAS = {
    "Tortillas": ["Tortilla de maíz"],
    "Pan": ["Pan blanco", "Pan dulce"],
    "Pollo y huevo": ["Pollo", "Huevo"],
    "Carne de res": ["Carne de res", "Vísceras de res"],
    "Carnes procesadas": ["Chorizo", "Jamón", "Salchichas", "Tocino"],
    "Lácteos": [
        "Leche pasteurizada y fresca",
        "Leche en polvo",
        "Leche evaporada, condensada y maternizada",
        "Crema de leche",
        "Queso amarillo",
        "Queso fresco",
        "Queso manchego o Chihuahua",
        "Queso Oaxaca o asadero",
        "Mantequilla",
    ],
    "Frutas": [
        "Aguacate",
        "Guayaba",
        "Limón",
        "Manzana",
        "Melón",
        "Naranja",
        "Papaya",
        "Piña",
        "Plátanos",
        "Sandía",
        "Uva",
    ],
    "Verduras": [
        "Calabacita",
        "Cebolla",
        "Chayote",
        "Chile poblano",
        "Chile serrano",
        "Ejotes",
        "Jitomate",
        "Lechuga y col",
        "Nopales",
        "Papa y otros tubérculos",
        "Pepino",
        "Tomate verde",
        "Zanahoria",
        "Frijol",
    ],
    "Bebidas": [
        "Jugos o néctares envasados",
        "Agua embotellada",
        "Refrescos envasados",
    ],
    "Medicamentos": [
        "Analgésicos",
        "Antibióticos",
        "Antigripales",
        "Cardiovasculares",
        "Dermatológicos",
        "Expectorantes y descongestivos",
    ],
    "Transporte foráneo": ["Autobús foráneo"],
    "Transporte aéreo": ["Transporte aéreo"],
    "Materiales de construcción": ["Materiales de construcción"],
}

CLAVES = {
    "Tortilla de maíz": ["A004"],
    "Pan blanco": ["A012"],
    "Pan dulce": ["A013", "A014"],
    "Pollo": ["A057", "A058", "A059"],
    "Carne de res": [
        "A025",
        "A026",
        "A028",
        "A029",
        "A030",
        "A031",
        "A032",
        "A033",
        "A034",
        "A035",
        "A036",
    ],
    "Vísceras de res": ["A037"],
    "Chorizo": ["A049"],
    "Jamón": ["A052"],
    "Salchichas": ["A055"],
    "Tocino": ["A054"],
    "Leche pasteurizada y fresca": ["A075"],
    "Leche en polvo": ["A078"],
    "Leche evaporada, condensada y maternizada": ["A077"],
    "Crema de leche": ["A089"],
    "Queso amarillo": ["A082"],
    "Queso fresco": ["A085"],
    "Queso manchego o Chihuahua": ["A086"],
    "Queso Oaxaca o asadero": ["A087"],
    "Mantequilla": ["A090"],
    "Huevo": ["A093"],
    "Aguacate": ["A108"],
    "Guayaba": ["A152"],
    "Limón": ["A154"],
    "Manzana": ["A158"],
    "Melón": ["A159"],
    "Naranja": ["A160"],
    "Papaya": ["A161"],
    "Piña": ["A163"],
    "Plátanos": ["A165", "A166", "A167"],
    "Sandía": ["A168"],
    "Uva": ["A169"],
    "Calabacita": ["A111"],
    "Cebolla": ["A112"],
    "Chayote": ["A113"],
    "Chile poblano": ["A116"],
    "Chile serrano": ["A117"],
    "Ejotes": ["A121"],
    "Jitomate": ["A124"],
    "Lechuga y col": ["A125", "A120"],
    "Nopales": ["A126"],
    "Papa y otros tubérculos": ["A101", "A102", "A103", "A104"],
    "Pepino": ["A127"],
    "Tomate verde": ["A129"],
    "Zanahoria": ["A130"],
    "Frijol": ["A137"],
    "Jugos o néctares envasados": ["A218"],
    "Agua embotellada": ["A215"],
    "Refrescos envasados": ["A220"],
    "Analgésicos": ["J029", "J030", "J053", "J054"],
    "Antibióticos": ["J028", "J052"],
    "Antigripales": ["J021", "J045"],
    "Cardiovasculares": ["J031", "J056"],
    "Dermatológicos": ["J022", "J046"],
    "Expectorantes y descongestivos": ["J024", "J025", "J048", "J049"],
    "Autobús foráneo": ["B006"],
    "Transporte aéreo": ["M003"],
    "Materiales de construcción": ["K038", "K040", "K042", "K044"],
}
